Inteface
kimitaWanjohi/school_lib pull request #4
Opened 2023-09-01 07:20 UTC by kimitaWanjohi

In this PR I did the following:
 - Create an `app.rb` for the crud functionality.
 - Add `main.rb` file for interacting with the app.rb crud functionality.

2023-09-01 07:53 UTC, danmainah requested changes
Hi @kimitaWanjohi , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️  Added the user interface and ensured it matches the design given
✔️  Ensured the user is able to add and view books.


# Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-09-01 07:53 UTC, danmainah commented on app.rb
> +
- [ ] @kimitaWanjohi I am unable to create a person(teacher or student) when I run your app, am getting the error below, kindly consider ensuring all options in the menu are working correctly.
![image](https://github.com/kimitaWanjohi/school_lib/assets/61408860/788b0214-37a5-46e5-a5ab-99f48d8fe302)

2023-09-01 07:53 UTC, danmainah commented on app.rb
> +    classroom = gets.chomp
- [ ] @kimitaWanjohi I can see you added an option for a student to enter their class, however, it's not part of the requirements in the console app design shown in the sneak peek, I would highly recommend sticking to the design given which is part of the project requirement.
![image](https://github.com/kimitaWanjohi/school_lib/assets/61408860/ad2fd37e-2d7c-482e-a597-6fb14bb02f47)

2023-09-02 19:06 UTC, merged

2023-09-02 20:12 UTC, Whoistolu reviewed
Hi @kimitaWanjohi 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

### You have submitted a project, that has been merged. Kindly reverse the merge before requesting a re-review.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @whoistolu in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-09-02 20:20 UTC, Whoistolu reviewed
Hi @kimitaWanjohi 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

### You have submitted a project, that has been merged. Kindly reverse the merge before requesting a re-review.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @whoistolu in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-09-02 21:09 UTC, Strangeal reviewed
Hi @kimitaWanjohi, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

**You have submitted a project, that has been merged. Kindly reverse the merge before requesting a re-review.**

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._